#Project Setup
general:
  productiveBranch: 'master'
  projectName: 'address-manager'

#Steps Specific Configuration
steps:
  mavenExecute:
#    dockerImage: 'maven:3.5.0-jdk-8'
    projectSettingsFile : ''

  deployToCfWithCli:
#    dockerImage: 's4sdk/docker-cf-cli'
    smokeTestStatusCode: '200'


#Stage Specific Configurations
stages:
  staticCodeChecks:
    findbugsExcludesFile: '' #Path to findbugs exclude file
    pmdExcludes: '' # List or ANT style patterns

  integrationTests:
    credentials:
      - alias: 'ERP_SYSTEM'
        credentialId: 'ERP_SYSTEM'

#  s4SdkQualityChecks:
#    jacocoExcludes:
#      - ''
#    nonErpDestinations:
#      - ''

  productionDeployment:
    cfTargets:
      - org: 'P2000934521trial_trial'
        space: 'dev'
        apiEndpoint: 'https://api.cf.eu10.hana.ondemand.com'
        appName: '	address-manager'
        manifest: 'manifest.yml'
        credentialsId: 'CF-DEPLOY'